version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: IDisposableAnalyzers
    versions:
    - 3.4.10
    - 3.4.11
    - 3.4.8
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: Unity.Container
    versions:
    - 5.11.10
